### ISSUE TITLE
Creating an Order

### ISSUE THREAD

**Issue by marinedic** [AgeWell/agewell-core#21] opened 2017-09-30 03:07 UTC
I went to create an order and the add item button is not working. Neither is the status or assign volunteer section. My order could not be completed, because I did not select a date which I was not able to do. The function was not working. I was able to add the price and notes easily.

**Comment by simplyspoke** [comment] 2017-12-25 02:01
Duplicate of closed issue

**Closed by simplyspoke** 2017-12-25 02:01 UTC
